### ISSUE TITLE
Please change your chunk labels

### ISSUE THREAD

**Issue by RaymondBalise** [kbroman/knitr_knutshell#12]
Hello Dr Broman,
I love https://kbroman.org/knitr_knutshell/ but I am reluctant to recommend it to my students because you currently use underscores in chunk labels.  Can you change them to use dashes?  I ask because the underscores will cause problems when students move to bookdown.

According to the Yihui in the [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/r-code.html):

> I strongly recommend that you only use alphanumeric characters (a-z, A-Z and 0-9) and dashes (-) in labels, because they are not special characters and will surely work for all output formats. Other characters, spaces and underscores in particular, may cause trouble in certain packages, such as bookdown.

Respectfully yours,
Ray

**Comment by kbroman** [comment]
Okay, thanks; I'll try.

**Comment by kbroman** [comment]
Implemented in PR #13.
