### ISSUE TITLE
http://kbroman.org/knitr_knutshell/pages/figs_tables.md does not exist

### ISSUE THREAD

**Issue by benmarwick** [kbroman/knitr_knutshell#2]
I was here http://kbroman.org/knitr_knutshell/pages/latex.html and followed the URL in this bit of text:
## Tables

To produce LaTeX tables, you can use kable and xtable [much as you would do with R Markdown](http://kbroman.org/knitr_knutshell/pages/figs_tables.md). And the results look considerably nicer than the html tables. Here’s a kable example.

And then got to 'Sorry this page does not exist.'

Thanks for making all this content available, by the way, it's a wonderful reference.

**Comment by kbroman** [comment]
Thanks! Now fixed.
