### ISSUE TITLE
Styling the Reports

### ISSUE THREAD

**Issue by andresalerno** [kbroman/knitr_knutshell#9]
Hi!

I have been working in a finance project using knitr (.Rmd) and I would like to know if there is possible to stylling the report, like:

- using some styling header with a logo
- contact information
- Name of the user of this information

As a matter of fact these options are some generic examples. The man idea here is to create and provide financial reports and they need some styling presentations.

Is that possible using it? I confess that I've been looking for this idea for a long.

Tks for your support, specially in your website!

André

**Comment by kbroman** [comment]
I'd recommend looking at [document templates](https://rmarkdown.rstudio.com/developer_document_templates.html). I don't have much experience with this myself.

**Comment by andresalerno** [comment]
No problem! Tks anyway!

Best
